
# ZervePulse Dashboard — Deployment Confirmation
# ─────────────────────────────────────────────────────────────

SCRIPT_ID   = "0ba6d1b6-796d-41f9-b4b3-0bda4675736e"
SCRIPT_NAME = "ZervePulse Dashboard"
RUN_CMD     = "streamlit run app/main.py --server.port 8080 --server.address 0.0.0.0"
TEMPLATE    = "Streamlit"
ENVIRONMENT = "Streamlit (c47aefed)"
COMPUTE     = "medium"

print("=" * 65)
print("  ⚡  ZERVEPULSE DASHBOARD — DEPLOYMENT CONFIRMATION")
print("=" * 65)
print(f"\n  Script Name  : {SCRIPT_NAME}")
print(f"  Script ID    : {SCRIPT_ID}")
print(f"  Template     : {TEMPLATE}")
print(f"  Environment  : {ENVIRONMENT}")
print(f"  Compute Size : {COMPUTE}")
print(f"  Run Command  : {RUN_CMD}")
print()
print("─" * 65)
print("  DEPLOYMENT URL:")
print("  ➜  Deploy via the Zerve UI: Open the script and click 'Deploy'")
print("  ➜  Once deployed, the URL will follow the pattern:")
print("     https://<your-org>.zerve.ai/app/<script-id>")
print()
print("─" * 65)
print("  ALL 4 SECTIONS IMPLEMENTED:")
print("  ✅  Section 1 — Command Center")
print("       • 6 metric cards (3×2 grid): 5,410 users, 64.8% churn,")
print("         1,625 high-risk, 0.7814 ROC-AUC, 22 Champions, 1,860 Ghosts")
print("       • Chart A: Persona distribution donut (5 segments)")
print("       • Chart B: Churn risk 3-bar (Low/Medium/High)")
print("       • Chart C: Onboarding impact 2-bar")
print()
print("  ✅  Section 2 — User Intelligence Lookup")
print("       • distinct_id text input + Analyse User Risk button")
print("       • Persona badge + churn probability (color-coded)")
print("       • 4 stat boxes: days_active, total_events,")
print("         unique_canvases, AI adoption %")
print("       • Top 3 SHAP risk drivers with user vs population mean")
print("       • Persona-specific action box")
print("       • Error message for unknown user IDs")
print()
print("  ✅  Section 3 — Full Churn Risk Leaderboard")
print("       • All 5,410 users, sorted by churn probability")
print("       • Filter: All / High Risk Only + Persona dropdown")
print("       • Export CSV button (⬇️)")
print("       • Paginated 50 per page (108 pages total)")
print("       • 10 columns: Rank, User ID, Persona, Churn Prob %,")
print("         Risk Level, Days Active, Canvases, AI Adoption %,")
print("         Total Events, Credits Used")
print("       • Row colors: red >0.7, amber 0.4–0.7, green <0.4")
print()
print("  ✅  Section 4 — Insights Explorer")
print("       • Chart 1: Avg canvases retained vs churned")
print("       • Chart 2: AI adoption retained vs churned")
print("       • Chart 3: Agent usage impact on churn")
print("       • Chart 4: Churn probability histogram (20 bins + thresholds)")
print("       • Top 6 Product Recommendations (FINDING/ACTION/IMPACT)")
print()
print("─" * 65)
print("  DATA SOURCES (loaded via zerve.variable):")
print("  • seg_df  → ZervePulse Persona Segmentation & BI Report")
print("  • seg_model → ZervePulse Persona Segmentation & BI Report")
print()
print("  DESIGN: Zerve dark theme (#1D1D20 bg, #fbfbff text,")
print("          #ffd400 gold, official palette throughout)")
print("=" * 65)